In [1]:
import pandas as pd

In [2]:
import os
os.getcwd()

'C:\\Users\\Dell'

In [10]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Dell\Downloads\archive\1_dirty_data.csv")
df

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,$7.25,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,$71.28,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,$7.93,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,$53.10,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,$8.05,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
901,622,623,1,3,"Nakid, Mr. Sahid",male,20.0,1,1,2653,$15.74,NaN,C
902,77,78,0,3,"Moutal, Mr. Rahamin Haim",male,NaN,0,0,374746,$8.05,NaN,S
903,715,716,0,3,"Soholt, Mr. Peter Andreas Lauritz Andersen",male,19.0,0,0,348124,$7.65,F G73,S
904,623,624,0,3,"Hansen, Mr. Henry Damsgaard",male,21.0,0,0,350029,$7.85,NaN,S
905,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,$23.45,NaN,S

In [9]:
df.isnull().sum()

Unnamed: 0       0
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            183
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          699
Embarked         2
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(15)

In [13]:
df.duplicated().sum()

np.int64(15)

In [14]:
df.dtypes

Unnamed: 0       int64
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp           object
Parch            int64
Ticket          object
Fare            object
Cabin           object
Embarked        object
dtype: object

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 906 entries, 0 to 905
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   906 non-null    int64
 1   PassengerId  906 non-null    int64
 2   Survived     906 non-null    int64
 3   Pclass       906 non-null    int64
 4   Name         906 non-null    object
 5   Sex          906 non-null    object
 6   Age          723 non-null    float64
 7   SibSp        906 non-null    object
 8   Parch        906 non-null    int64
 9   Ticket       906 non-null    object
 10  Fare         906 non-null    object
 11  Cabin        207 non-null    object
 12  Embarked     904 non-null    object
dtypes: float64(1), int64(5), object(7)
memory usage: 92.1+ KB

In [16]:
df.describe()

       Unnamed: 0  PassengerId    Survived      Pclass         Age       Parch
count  906.000000   906.000000  906.000000  906.000000  723.000000  906.000000
mean   447.181015   448.181015    0.384106    2.311258   29.684882    0.379691
std    257.105293   257.105293    0.486652    0.837139   14.474664    0.802886
min      0.000000     1.000000    0.000000    1.000000    0.420000    0.000000
25%    225.250000   226.250000    0.000000    2.000000   20.000000    0.000000
50%    448.500000   449.500000    0.000000    3.000000   28.000000    0.000000
75%    668.750000   669.750000    1.000000    3.000000   38.000000    0.000000
max    890.000000   891.000000    1.000000    3.000000   80.000000    6.000000

In [23]:
df.isnull().sum()

Unnamed: 0     0
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [25]:
df.columns

Index(['Unnamed: 0', 'PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age',
       'SibSp', 'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [26]:
df=df.drop_duplicates()
df

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,$7.25,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,$71.28,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,$7.93,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,$53.10,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,$8.05,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,$13.00,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,$30.00,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,$23.45,S
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,$30.00,C
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,$7.75,Q

In [28]:
df.duplicated().sum()

np.int64(0)

In [34]:
df=df.replace('male','Male')

df

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",Male,22.0,1,0,A/5 21171,$7.25,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",FeMale,38.0,1,0,PC 17599,$71.28,C
2,2,3,1,3,"Heikkinen, Miss. Laina",FeMale,26.0,0,0,STON/O2. 3101282,$7.93,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",FeMale,35.0,1,0,113803,$53.10,S
4,4,5,0,3,"Allen, Mr. William Henry",Male,35.0,0,0,373450,$8.05,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,2,"Montvila, Rev. Juozas",Male,27.0,0,0,211536,$13.00,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",FeMale,19.0,0,0,112053,$30.00,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",FeMale,28.0,1,2,W./C. 6607,$23.45,S
889,889,890,1,1,"Behr, Mr. Karl Howell",Male,26.0,0,0,111369,$30.00,C
890,890,891,0,3,"Dooley, Mr. Patrick",Male,32.0,0,0,370376,$7.75,Q

In [35]:
df=df.replace('FeMale','female')

In [50]:
df

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",Male,22.0,1,0,A/5 21171,$7.25,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,$71.28,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,$7.93,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,$53.10,S
4,4,5,0,3,"Allen, Mr. William Henry",Male,35.0,0,0,373450,$8.05,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,2,"Montvila, Rev. Juozas",Male,27.0,0,0,211536,$13.00,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,$30.00,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,$23.45,S
889,889,890,1,1,"Behr, Mr. Karl Howell",Male,26.0,0,0,111369,$30.00,C
890,890,891,0,3,"Dooley, Mr. Patrick",Male,32.0,0,0,370376,$7.75,Q

In [37]:
df["Sex"].unique()

array(['Male', 'female', 'F'], dtype=object)

In [38]:
df=df.replace('F','female')

In [39]:
df["Sex"].unique()

array(['Male', 'female'], dtype=object)

In [40]:
df["Embarked"].unique()

array(['S', 'C', 'Q', 'Queenstown'], dtype=object)

In [41]:
df=df.replace('Queenstown','Q')

In [42]:
df["Embarked"].unique()

array(['S', 'C', 'Q'], dtype=object)

In [43]:
df.columns

Index(['Unnamed: 0', 'PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age',
       'SibSp', 'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [44]:
df.describe()

       Unnamed: 0  PassengerId    Survived      Pclass         Age       Parch
count  891.000000   891.000000  891.000000  891.000000  891.000000  891.000000
mean   445.000000   446.000000    0.383838    2.308642   29.361582    0.381594
std    257.353842   257.353842    0.486592    0.836071   13.019697    0.806057
min      0.000000     1.000000    0.000000    1.000000    0.420000    0.000000
25%    222.500000   223.500000    0.000000    2.000000   22.000000    0.000000
50%    445.000000   446.000000    0.000000    3.000000   28.000000    0.000000
75%    667.500000   668.500000    1.000000    3.000000   35.000000    0.000000
max    890.000000   891.000000    1.000000    3.000000   80.000000    6.000000

In [46]:
Q1=df["Age"].quantile(0.25)
Q3=df["Age"].quantile(0.75)
IQR=Q3-Q1
lower=Q1-1.5*IQR
Upper=Q3+1.5*IQR
outliers=df[(df["Age"]<lower) | (df["Age"]>upper)]
print("Lower Limit:", lower)
print("Upper Limit:", Upper)
print("Number of Outliers")
len(outliers)

Lower Limit: 2.5
Upper Limit: 54.5
Number of Outliers

66

In [47]:
outliers.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
7,7,8,0,3,"Palsson, Master. Gosta Leonard",Male,2.0,3,1,349909,$21.08,S
11,11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,$26.55,S
15,15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,$16.00,S
16,16,17,0,3,"Rice, Master. Eugene",Male,2.0,4,1,382652,$29.13,Q
33,33,34,0,2,"Wheadon, Mr. Edward H",Male,66.0,0,0,C.A. 24579,$10.50,S

In [52]:
df["Fare"]=df["Fare"].str.replace("$","",regex=False)
df["Fare"]=pd.to_numeric(df["Fare"])

In [53]:
Q1 = df["Fare"].quantile(0.25)
Q3 = df["Fare"].quantile(0.75)
IQR = Q3-Q1
lower=Q1-1.5*IQR
Upper=Q3+1.5*IQR
outliers=df[(df["Fare"]<lower) | (df["Fare"]>upper)]
print("Lower Limit:", lower)
print("Upper Limit:", Upper)
print("Number of Outliers")
len(outliers)

Lower Limit: -26.7125
Upper Limit: 65.6275
Number of Outliers

141

In [54]:
df.dtypes

Unnamed: 0       int64
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp           object
Parch            int64
Ticket          object
Fare           float64
Embarked        object
dtype: object

In [57]:
df[df["SibSp"]=="one"]

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
98,98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,one,1,231919,23.00,S
104,104,105,0,3,"Gustafsson, Mr. Anders Vilhelm",Male,37.0,one,0,3101276,7.93,S
499,499,500,0,3,"Svensson, Mr. Olof",Male,24.0,one,0,350035,7.80,S

In [62]:
df["SibSp"]=df["SibSp"].replace("one",1)

In [63]:
df["SibSp"].unique()

array([1, 0, 3, 4, 2, 5, 8])

In [60]:
df["SibSp"]=df["SibSp"].astype(int)

In [64]:
df["SibSp"].dtype

dtype('int64')

In [69]:
df.columns

Index(['Unnamed: 0', 'PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age',
       'SibSp', 'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [70]:
print(df.columns.tolist())

['Unnamed: 0', 'PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Embarked']

In [71]:
df.columns=df.columns.str.strip()

In [72]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [80]:
df.to_csv(r"C:\Users\Dell\OneDrive\Documents\internship projects\cleaned_titanic.csv",index=False)

In [74]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",Male,22.0,1,0,A/5 21171,7.25,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.28,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.93,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.10,S
4,5,0,3,"Allen, Mr. William Henry",Male,35.0,0,0,373450,8.05,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",Male,27.0,0,0,211536,13.00,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.45,S
889,890,1,1,"Behr, Mr. Karl Howell",Male,26.0,0,0,111369,30.00,C
890,891,0,3,"Dooley, Mr. Patrick",Male,32.0,0,0,370376,7.75,Q

In [77]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [78]:
df.duplicated().sum()

np.int64(0)